name: YouTube_Premium_Final_Success

on:
  workflow_dispatch:
    inputs:
      decrypted_youtube_url:
        description: "https://www.dropbox.com/scl/fi/3yzrrpgdtmqdbz4kce96w/youtube-v20.21.6.ipa?rlkey=qd5kedk8aqh09ko6gya08474x&st=vw0kkj7l&dl=1"
        default: "https://www.dropbox.com/scl/fi/3yzrrpgdtmqdbz4kce96w/youtube-v20.21.6.ipa?rlkey=qd5kedk8aqh09ko6gya08474x&st=vw0kkj7l&dl=1"
        required: true
        type: string

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Tools
        run: |
          brew install ldid
          git clone https://github.com/Al4ise/Azule ~/Azule
          chmod +x ~/Azule/azule

      - name: Download Files
        run: |
          # Tải IPA từ Dropbox (link của bạn rất tốt)
          curl -L "${{ github.event.inputs.decrypted_youtube_url }}" -o youtube.ipa
          
          # Tải Tweak với cờ -f để ép tải lại nếu lỗi
          curl -Lf "https://github.com/BalackBurn/YTLite/releases/download/v5.0.1/com.dvntm.ytlite_5.0.1_iphoneos-arm64.deb" -o ytlite.deb
          
          # Kiểm tra file và dung lượng (YTLite phải > 1MB)
          ls -lh youtube.ipa ytlite.deb

      - name: Final Inject
        run: |
          # Sử dụng sudo và đường dẫn hiện tại để tránh lỗi "Inappropriate file type"
          # -n: Tên app, -b: Bundle ID cài song song
          sudo ~/Azule/azule -i ./youtube.ipa -f ./ytlite.deb -n "YouTube Premium" -b "com.google.ios.youtube.premium" -o .

      - name: Upload Final Product
        uses: actions/upload-artifact@v4
        with:
          name: YouTube_Premium_Done
          path: "*.ipa"
