name: YouTube_Premium_Fix_Final

on:
  workflow_dispatch:
    inputs:
      decrypted_youtube_url:
        description: "https://www.dropbox.com/scl/fi/3yzrrpgdtmqdbz4kce96w/youtube-v20.21.6.ipa?rlkey=qd5kedk8aqh09ko6gya08474x&st=vw0kkj7l&dl=1"
        default: "https://www.dropbox.com/scl/fi/3yzrrpgdtmqdbz4kce96w/youtube-v20.21.6.ipa?rlkey=qd5kedk8aqh09ko6gya08474x&st=vw0kkj7l&dl=1"
        required: true
        type: string

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies (QUAN TRỌNG)
        run: |
          # Cài đặt dpkg để xử lý file .deb chuẩn mới (Sửa lỗi Inappropriate file type)
          brew install dpkg ldid
          
          # Tải Azule
          git clone https://github.com/Al4ise/Azule ~/Azule
          chmod +x ~/Azule/azule

      - name: Download Files
        run: |
          # 1. Tải IPA từ Dropbox
          curl -L "${{ github.event.inputs.decrypted_youtube_url }}" -o youtube.ipa
          
          # 2. Tải Tweak YTLitePlus (Bản ổn định hơn YTLite thường)
          # Link này là bản Release chính thức, ít lỗi nén
          curl -L "https://github.com/BalackBurn/YTLitePlus/releases/download/v19.21.3-4.0.0/com.dvntm.ytliteplus_19.21.3-4.0.0_iphoneos-arm64.deb" -o ytlite.deb
          
          # 3. KIỂM TRA FILE (Debug)
          # Lệnh này sẽ in ra loại file thực sự để đảm bảo không phải HTML lỗi
          file ytlite.deb
          ls -lh ytlite.deb

      - name: Inject and Build
        run: |
          # Sử dụng đường dẫn tuyệt đối $(pwd)
          # Tweak YTLitePlus đã bao gồm Logo Premium và chặn quảng cáo
          
          ~/Azule/azule -i "$(pwd)/youtube.ipa" \
                        -f "$(pwd)/ytlite.deb" \
                        -n "YouTube Premium" \
                        -b "com.google.ios.youtube.premium" \
                        -o "$(pwd)"

      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: YouTube_Premium_Done
          path: "*.ipa"
